feature: install symfony
LeoGrouet/Qui-Paie-Quoi pull request #1
Opened 2024-04-23 14:06 UTC by LeoGrouet

2024-04-23 14:28 UTC, clementvtrd requested changes
Tu peux également faire une passe sur tous les commentaires et le .gitignore généré pour supprimé les parties qui sont inutiles (vu que seul le .env doit être ignore)

2024-04-23 14:28 UTC, clementvtrd commented on App/.env
Hehehehehe NOPE

2024-04-23 14:28 UTC, clementvtrd commented on App/.env
À ajouter au .gitignore + créer un `.env.dist` avec les valeurs vides

2024-04-23 14:28 UTC, clementvtrd commented on App/.env
On va mettre une stack "classique" docker compose en place, on va utiliser le contenu du .env comme unique source des variables par environnement (au lieu de la stratégie utilisée par Symfony qui merge les .env avec un ordre de priorité selon le nom du fichier)
Pour se faire il faut maintenir une version _template_ du .env (le .env.dist) et ignorer le `.env` dans git. Le .env.dist contient les valeurs de dev de chaque variables (example : nom de domain = localhost, etc...)

2024-04-23 15:10 UTC, LeoGrouet commented on App/.env
Done.

2024-04-24 13:11 UTC, clementvtrd requested changes

2024-04-24 13:11 UTC, clementvtrd commented on App/config/services.yaml
> +      - "../src/Kernel.php"
Tu peux supprimer cette partie : nous définirons manuellement nos services (on fonctionnera avec une _whitelist_ au lieu d'une _blacklist_ pour leur déclaration)
```suggestion
```

2024-04-24 13:14 UTC, LeoGrouet commented on App/config/services.yaml
> +      - "../src/Kernel.php"
C'est fait

2024-04-24 13:15 UTC, clementvtrd approved these changes

2024-04-24 13:50 UTC, merged