feat: CI and settings git
LeoGrouet/Qui-Paie-Quoi pull request #10
Opened 2024-07-01 11:55 UTC by LeoGrouet

2024-07-01 12:30 UTC, clementvtrd requested changes
Cette PR est en draft : nous la complèterons avec PHP CS Fixer et PHP Stan une fois les outils mis en place !

2024-07-01 12:30 UTC, clementvtrd commented on .vscode/settings.json
Ce fichier ne doit pas être versionner. Chaque développeur est responsable des paramètres de sa machine. Tu peux créer un fichier `~/.gitignore` dans ton _home directory_ et utiliser la commande `git config --global core.excludesFile $HOME/.gitignore` pour indiquer à Git l'existence de ce super-gitignore 👍

2024-07-02 09:19 UTC, LeoGrouet commented on .vscode/settings.json
done

2024-07-02 09:40 UTC, clementvtrd requested changes

2024-07-02 09:40 UTC, clementvtrd commented on .vscode/settings.json
Je vois toujours ton fichier 👀 
Tu peux le supprimer de git avec la commande `git rm --cached .vscode/settings.json`

2024-07-02 11:10 UTC, LeoGrouet commented on .vscode/settings.json
done

2024-07-05 14:05 UTC, clementvtrd requested changes
Pour terminer cette PR il te faudra également ajouter des étapes à ta CI pour lancer automatiquement PHP Stan et PHP CS Fixer sur tes prochains commits afin d'éviter de merger des erreurs de type ou de lint dans ta branche principale 👍 Dans un premier temps corrige les quelques retours, ensuite nous ferons du pair pour que tu vois comment fonction un workflow Github. Tu peux également prendre un peu de temps pour te renseigner de ton côté et essayer de faire le workflow de tes rêves

2024-07-05 14:05 UTC, clementvtrd commented on App/src/Command/HandleBalanceCommand.php
> +        $this->outputBalance($id | null, $output);
Si tu n'as pas d'ID, tu ne peux pas afficher de balance ? Autant afficher une erreur à la manière du la variable $name juste au dessus 👍

2024-07-05 14:05 UTC, clementvtrd commented on App/src/Entity/Bilan.php
> +
Extra line pas utile 👍

2024-07-05 14:05 UTC, clementvtrd commented on App/src/Entity/Bilan.php
> +    /**
Tu peux séparer tes propriétés qui ont du PHPDOC avec un saut de ligne supplémentaire 👍 
```suggestion

    /**
```

2024-07-05 14:05 UTC, clementvtrd commented on App/src/Entity/Bilan.php
BTW tes propriétés peuvent probablement être private vu que tu n'hérite pas de ta classe

2024-07-05 14:05 UTC, clementvtrd commented on App/src/Repository/ExpenseRepository.php
> +     * @return Expense[]
PHP CS Fixer ajoute un saut de ligne avant l'annotation `@return` 👀 
```suggestion
     * @param int $groupId

     * @return Expense[]
```

2024-07-05 14:05 UTC, clementvtrd commented on App/src/Repository/GroupRepository.php
> +        if ($group !== null && !$group instanceof Group) {
Écrit de la sorte, je trouve que ta condition est plus intelligible en lecture

```suggestion
        if ($group === null || !$group instanceof Group) {
```

2024-07-05 14:05 UTC, clementvtrd commented on App/src/Repository/UserRepository.php
> +        if ($user !== null && !$user instanceof User) {
```suggestion
        if ($user === null || !$user instanceof User) {
```

2024-07-05 14:05 UTC, clementvtrd commented on Makefile
Tu peux également ajouter un raccourcie pour lancer PHP CS Fixer 🆗

2024-07-08 08:02 UTC, LeoGrouet commented on App/src/Command/HandleBalanceCommand.php
> +        $this->outputBalance($id | null, $output);
done

2024-07-08 08:02 UTC, LeoGrouet commented on App/src/Entity/Bilan.php
> +
done

2024-07-08 08:03 UTC, LeoGrouet commented on App/src/Entity/Bilan.php
> +    /**
done

2024-07-08 08:03 UTC, LeoGrouet commented on App/src/Entity/Bilan.php
done

2024-07-08 08:04 UTC, LeoGrouet commented on App/src/Repository/ExpenseRepository.php
> +     * @return Expense[]
done

2024-07-08 08:05 UTC, LeoGrouet commented on App/src/Repository/GroupRepository.php
> +        if ($group !== null && !$group instanceof Group) {
done

2024-07-08 08:06 UTC, LeoGrouet commented on App/src/Repository/UserRepository.php
> +        if ($user !== null && !$user instanceof User) {
done

2024-07-08 08:06 UTC, LeoGrouet commented on Makefile
Oui complètement :)

2024-07-08 12:46 UTC, clementvtrd requested changes

2024-07-08 12:46 UTC, clementvtrd commented on .github/workflows/ci.yaml
> +        uses: actions/checkout@v4
```suggestion
      - uses: actions/checkout@v4
```

2024-07-08 12:46 UTC, clementvtrd commented on .php-cs-fixer.cache
Ne doit pas être commit :)

2024-07-08 12:46 UTC, clementvtrd commented on App/phpstan.dist.neon
> +    level: 9
```suggestion
    level: max
```

2024-07-08 12:46 UTC, clementvtrd commented on .github/workflows/ci.yaml
> +        uses: actions/checkout@v4
+ les étapes d'installation du projet pour expliquer les étapes à Github Action (docker build ; composer install ; etc...)

2024-07-09 08:39 UTC, clementvtrd requested changes

2024-07-09 08:39 UTC, clementvtrd commented on Makefile
> +	php-cs-fixer check App/src
```suggestion
.PHONY=phpcsfixer
phpcsfixer:
	docker compose run --rm php vendor/bin/php-cs-fixer fix App/src

.PHONY=phpcsfixer-dev
phpcsfixer-dev:
	docker compose run --rm php vendor/bin/php-cs-fixer check App/src
```

2024-07-09 11:29 UTC, LeoGrouet commented on Makefile
> +	php-cs-fixer check App/src
done

2024-07-09 14:20 UTC, clementvtrd requested changes

2024-07-09 14:20 UTC, clementvtrd commented on .github/workflows/ci.yaml
> +        run : cp App/.env.dist App/.env
```suggestion
      - name: Initialize .env files
        run : |
          echo GID=$(id -g) > .env
          echo UID=$UID >> .env
          cp App/.env.dist App/.env

      - name: Build Docker image
        run : docker compose build
```

2024-07-09 14:20 UTC, clementvtrd commented on .github/workflows/ci.yaml
> +        run : docker compose run --rm php composer install --no-scripts
Un petit `make install` serait + pratique, même pour le bootstrap de ton projet pour un dév :)

2024-07-09 14:23 UTC, LeoGrouet commented on .github/workflows/ci.yaml
> +        run : docker compose run --rm php composer install --no-scripts
done

2024-07-09 14:57 UTC, clementvtrd requested changes

2024-07-09 14:57 UTC, clementvtrd commented on .github/workflows/ci.yaml
> +          make composer-install
Alors du coup le composer install ne devrait avoir lieu qu'une fois le build php fait, sinon tu te retrouve avec les logs du build de l'image au moment du make composer-install, qui n'est pas censé arrivé

2024-07-09 14:57 UTC, clementvtrd commented on .github/workflows/ci.yaml
> +        run : docker compose build
Pour éviter de build trop, tu peux préciser que tu build l'image de php
```sh
docker compose build php
```

2024-07-09 15:09 UTC, LeoGrouet commented on .github/workflows/ci.yaml
> +          make composer-install
done

2024-07-09 15:09 UTC, LeoGrouet commented on .github/workflows/ci.yaml
> +        run : docker compose build
done

2024-07-09 15:14 UTC, clementvtrd approved these changes

2024-07-09 15:15 UTC, merged