Group creation feature
LeoGrouet/Qui-Paie-Quoi pull request #14
Opened 2024-08-08 14:21 UTC by LeoGrouet

This feature allow a user log in the app to create a group and save it in DB.

2024-08-22 13:26 UTC, clementvtrd requested changes

2024-08-22 13:26 UTC, clementvtrd commented on App/.phpunit.result.cache
Tu peux supprimer ce cache et l'ajouter au .gitignore 👍

2024-08-22 13:26 UTC, clementvtrd commented on App/public/css/addGroup.css
> +}
N'hésite pas à éclaircir tes groupes de style. Peut être qu'un outil comme [stylelint](https://stylelint.io) pourrait être ajouter entre deux PR pour former tes fichiers CSS 😉

2024-08-22 13:26 UTC, clementvtrd commented on App/public/css/groupPage.css
>      height: var(--height-l);
Tu peux ajouter `width: auto;` pour t'assurer que l'image garde son ratio 👍

2024-08-22 13:26 UTC, clementvtrd commented on App/public/css/groupPage.css
> +    width: auto;
Je ne suis pas sûr que ça soit nécessaire étant donné que tu as un bloc en display flex avec un flex-grow 1 🤔 
À double check

2024-08-22 13:26 UTC, clementvtrd commented on App/src/Controller/Group/GroupBalanceController.php
> +    #[Route('/groups/{id}/balance', name: 'groups_balance', methods: ['GET'])]
Pour les méthodes, tu peux utiliser les constantes + ne pas mettre de tableau si jamais tu n'en a qu'une seule :
```suggestion
    #[Route('/groups/{id}/balance', name: 'groups_balance', methods: Request::METHOD_GET)]
```

2024-08-22 13:26 UTC, clementvtrd commented on App/src/Controller/Group/GroupExpensesController.php
Même remarque que pour App/src/Controller/Group/GroupBalanceController.php pour les constantes

2024-08-22 13:26 UTC, clementvtrd commented on App/src/Controller/Group/GroupsPageController.php
Même remarque que pour App/src/Controller/Group/GroupBalanceController.php pour les constantes

2024-08-22 13:26 UTC, clementvtrd commented on App/src/Controller/Group/GroupsPageController.php
> +        $groups = $groupRepository->findAll();
Que se passe-t-il si jamais tu as 12 784 123 groupes ? 😈

2024-08-22 13:26 UTC, clementvtrd commented on App/src/Entity/Group.php
> +        private ?Collection $users,
Pourquoi avoir passer cette collection en nullable ? 🤔 Je ne pense pas qu'il peut y avoir un groupe avec 0 utilisateurs au niveau métier
Niveau Doctrine, une Collection vide sera dans tous les cas injectée dans ton entité

2024-08-22 13:26 UTC, clementvtrd commented on App/src/Form/GroupType.php
> +                            max: 60,
Pourquoi min: 1 ? max: 60 ? 😄

2024-08-22 13:26 UTC, clementvtrd commented on App/src/Form/GroupType.php
> +                            max: 180,
De même ici, pourquoi ce choix de valeur ?

2024-08-22 13:46 UTC, MaelBriantin requested changes

2024-08-22 13:46 UTC, MaelBriantin commented on App/src/Controller/Group/GroupExpensesController.php
Since you created a new group folder to put all your group related controllers in, maybe you can just call them ExpenseController and PageController.

2024-08-22 13:46 UTC, MaelBriantin commented on App/src/Controller/Group/GroupsPageController.php
Same as previous comment.

2024-08-22 13:46 UTC, MaelBriantin commented on App/src/Controller/Group/GroupBalanceController.php
Same as next comment.

2024-08-22 13:46 UTC, MaelBriantin commented on App/src/Entity/Group.php
Does this means that a group can exist without associated user (simple question)?

2024-08-22 13:46 UTC, MaelBriantin commented on App/templates/group/addGroup.html.twig
Some indentation issues between your <div> and {{ form }}. Tab missing.

2024-08-22 13:46 UTC, MaelBriantin commented on App/templates/group/groupExpenses.html.twig
Same comment as for the controllers. App/templates/group/expenses.html.twig seems better for reading.

2024-08-26 13:21 UTC, LeoGrouet commented on App/.phpunit.result.cache
Done

2024-08-26 13:22 UTC, LeoGrouet commented on App/public/css/addGroup.css
> +}
Eclaircir comme ceci ? 
```
.add_group_form, .add_group_form>form{
    display: flex;
    width: 100%;
    flex-direction: column;
    flex-grow: 1;
    position: relative;

    footer{
        display: flex;
        flex-direction: column;
        justify-content: flex-end;
        flex-grow: 1;
    } 
}
```

2024-08-26 13:23 UTC, LeoGrouet commented on App/public/css/groupPage.css
>      height: var(--height-l);
done

2024-08-26 13:26 UTC, LeoGrouet commented on App/public/css/groupPage.css
> +    width: auto;
Effectivement, ca n'as pas l'air utile

2024-08-26 13:30 UTC, LeoGrouet commented on App/src/Controller/Group/GroupBalanceController.php
> +    #[Route('/groups/{id}/balance', name: 'groups_balance', methods: ['GET'])]
done

2024-08-26 13:33 UTC, LeoGrouet commented on App/src/Controller/Group/GroupsPageController.php
> +        $groups = $groupRepository->findAll();
Je pensais laisser comme ça pour l'instant et gérer uniquement les groupes auxquels l'utilisateur connecté est rattaché .. Mais c'est pas une mauvaise chose de le mettre maintenant finalement

2024-08-26 14:40 UTC, LeoGrouet commented on App/public/css/groupPage.css
> +    width: auto;
Si si ca me permet d'avoir mon bouton en bas de la page

Avec : 
![Capture d’écran du 2024-08-26 16-39-24](https://github.com/user-attachments/assets/97165bc0-bd0c-4a57-83c8-cb34a38b5e64)

Sans : 
![Capture d’écran du 2024-08-26 16-40-00](https://github.com/user-attachments/assets/29fd2d5a-3d91-45de-86e9-d25797f8d34a)

2024-08-26 15:33 UTC, LeoGrouet commented on App/src/Entity/Group.php
> +        private ?Collection $users,
prout

2024-08-26 15:35 UTC, LeoGrouet commented on App/src/Form/GroupType.php
> +                            max: 60,
Min 1 ok, j'ai mis à 5 pour avoir au moins un truc qui veux dire quelque chose
Et 60 pour refléter ce qui est indiqué dans l'entité

2024-08-26 15:36 UTC, LeoGrouet commented on App/src/Form/GroupType.php
> +                            max: 180,
A l'inverse en effet, on peux mettre 0 en min si il n'y as pas besoin de description , et 180 pour refléter ce qui est indiqué dans l'entité

2024-08-26 15:37 UTC, LeoGrouet commented on App/src/Controller/Group/GroupExpensesController.php
c'est pas faux

2024-08-26 15:38 UTC, LeoGrouet commented on App/src/Entity/Group.php
?? C'était quoi la ligne de code ?

2024-08-26 15:39 UTC, LeoGrouet commented on App/templates/group/addGroup.html.twig
done

2024-08-26 15:39 UTC, LeoGrouet commented on App/templates/group/groupExpenses.html.twig
Where ?

2024-08-28 09:32 UTC, clementvtrd reviewed
Le nom de tes controllers (`Group/BalanceController` ; `Group/ExpensesController` ; `Group/PageController`) me laisse un peu perplexe 🤔
Je pense que le dernier peut être renommer. Par exemple un controller qui liste les groupes et permet d'en créer / supprimer sur la même pas peut s'appeler IndexController (de manière générique quelque soit l'entité)
Tu peux avoir un namespace un peu plus précis quand tu change d'entité. Typiquement : `Controller/Group/Balance/ShowController` ou encore `Controller/Group/Expense/IndexController` 👍

2024-08-28 09:32 UTC, clementvtrd commented on App/public/css/addGroup.css
Pour les fichier CSS, je suis assez partisan d'ajouter des espaces avant les accolades ouvrantes et autour des sélecteurs du type `>`.
Peut être mettre en place stylelint afin de normer  tout ça

2024-08-28 09:32 UTC, clementvtrd commented on App/public/css/groupPage.css
> +    width: auto;
Le `width: auto` ?

2024-08-28 09:32 UTC, clementvtrd commented on App/public/js/flashMessageDisplayer.js
Je pense que tu peux ajouter une petite couche de CSS à ta classe `flash-message` afin d'obtenir une petite animation pour masquer l'élément. De mémoire pour faire simple il faut

1. faire une transition horizontal pour envoyer la notification hors de l'écran (e.g.: `transform: translateY(500`) avec une transition pour animer le tout.
2. après un délais correspondant à la durée de ta transition retirer l'élément du DOM HTML (tu peux prends une marge genre 2 fois le délais pour éviter que ça ne disparaisse trop tôt)

2024-08-28 09:36 UTC, clementvtrd requested changes

2024-08-28 09:36 UTC, clementvtrd commented on App/templates/base.html.twig
> +           <script src="{{ asset('js/flashMessageDisplayer.js') }}" defer >  </script>
Question de lecture je trouve plus pratique d'avoir les _flags_ en début de balise HTML. De plus tu peux essayer de n'avoir qu'un attribut HTML par ligne, si tu en as plus d'un tu peux ajouter des sauts de ligne systématiquement pour rendre ton HTML + lisible
```suggestion
           <script
              defer
              src="{{ asset('js/flashMessageDisplayer.js') }}"
           ></script>
```

2024-08-28 09:36 UTC, clementvtrd commented on App/templates/group/groups.html.twig
>          {% endfor %}
```suggestion
      {% if groups is empty %}
        <p class="group_is_empty">Vous n'appartenez à aucun groupe</p>
      {% else %}
        {% for group in groups %}
            <a class="group_info" href="{{ path ('groups_balance', {id:group.id}) }}">
              {{group.name}}
            </a>
        {% endfor %}
      {% endif %}
```

2024-08-28 12:33 UTC, LeoGrouet commented on App/public/css/groupPage.css
> +    width: auto;
Non en effet le display : flex suffit

2024-08-28 12:33 UTC, LeoGrouet commented on App/public/css/addGroup.css
Prochaine PR ?

2024-08-28 13:45 UTC, LeoGrouet commented on App/templates/base.html.twig
> +           <script src="{{ asset('js/flashMessageDisplayer.js') }}" defer >  </script>
Okay je vais essayer d'appliquer ça

2024-08-28 13:48 UTC, LeoGrouet commented on App/templates/group/groups.html.twig
>          {% endfor %}
Done

2024-08-29 05:52 UTC, LeoGrouet commented on App/public/js/flashMessageDisplayer.js
Done ( je vais garder le opacity pour l'instant ) et je verrais avec Arthur ce qu'il veux faire au cas ou il veuille changer

2024-09-05 08:15 UTC, clementvtrd approved these changes

2024-09-05 08:15 UTC, clementvtrd commented on App/templates/base.html.twig
> +           src="{{ asset('js/flashMessageDisplayer.js') }}"
```suggestion
             defer 
             src="{{ asset('js/flashMessageDisplayer.js') }}" 
```

2024-09-05 09:16 UTC, merged