Feat/phpunit
LeoGrouet/Qui-Paie-Quoi pull request #17
Opened 2024-08-26 12:07 UTC by LeoGrouet

2024-08-28 09:22 UTC, clementvtrd requested changes
You can also add a new step on your `.github/workflows/ci.yaml` to run oh-unit after php cs fixer and phpstan 👍

2024-08-28 09:22 UTC, clementvtrd commented on App/src/Service/ExpenseBalancer.php
> +        readonly private EntityManagerInterface $entityManager
```suggestion
        private readonly EntityManagerInterface $entityManager
```

2024-08-28 09:22 UTC, clementvtrd commented on App/src/Service/ExpenseBalancer.php
> +        $amountByParticipants = $amount / count($participants);
Que se passe-t-il s'il y a 0 participants ? 🤡

2024-08-28 09:22 UTC, clementvtrd commented on App/src/Service/ExpenseBalancer.php
> +    }
Cette partie là correspond à ce que l'on peut appeler un `upsert` (`update` + `insert`)
Je pense que pour les gros groupes tu peux prévoir une query dans dans repository qui se charge de faire ce `upsert` via une query Doctrine :

- on cherche la balance pour un groupe et un utilisateur donné
- si la balance existe on la retourne
- sinon on en créait une nouvelle et on la retourne

2024-08-28 09:22 UTC, clementvtrd commented on App/tests/Entity/UserTest.php
It missed some tests here. First you can ensure the entity user implements the Symfony Security interfaces, then check all getter/setter works

2024-08-29 06:28 UTC, LeoGrouet commented on App/src/Service/ExpenseBalancer.php
> +        readonly private EntityManagerInterface $entityManager
Done

2024-08-29 06:39 UTC, LeoGrouet commented on App/src/Service/ExpenseBalancer.php
> +        $amountByParticipants = $amount / count($participants);
hum...

2024-08-29 12:57 UTC, LeoGrouet commented on App/src/Service/ExpenseBalancer.php
> +    }
Done

2024-09-04 07:13 UTC, LeoGrouet commented on App/tests/Entity/UserTest.php
Done

2024-09-05 08:17 UTC, clementvtrd requested changes

2024-09-05 08:17 UTC, clementvtrd commented on App/tests/Services/ExpenseBalancerTest.php
![nope](https://i.giphy.com/ui4VjMUBGXhwgdwUnK.webp)

2024-09-05 08:20 UTC, LeoGrouet commented on App/tests/Services/ExpenseBalancerTest.php
huhum... héhéhé

2024-09-11 08:33 UTC, clementvtrd approved these changes

2024-09-11 08:33 UTC, clementvtrd commented on App/.phpunit.result.cache
Fichier à supprimer et à ajouter au `.gitignore` 😉

2024-09-11 08:33 UTC, clementvtrd requested changes
Trompé de bouton, voir le message sur le cache de phpunit

2024-09-11 08:52 UTC, LeoGrouet commented on App/.phpunit.result.cache
Le fichier était déja dans le gitignore, c'est bizare

2024-09-11 12:10 UTC, clementvtrd approved these changes

2024-09-11 12:19 UTC, merged