Creation expense
LeoGrouet/Qui-Paie-Quoi pull request #19
Opened 2024-09-10 12:34 UTC by LeoGrouet

La PR PHP unit n'est pas merge  donc je n'ai pas mis le test pour l'instant, mais ca va venir.

2024-09-11 08:36 UTC, clementvtrd requested changes

2024-09-11 08:36 UTC, clementvtrd commented on App/src/DTO/ExpenseDTO.php
Missing tests

2024-09-11 08:36 UTC, clementvtrd commented on App/src/Entity/User.php
You don't need this IMO, you can just use the getUsername function 👍

2024-09-11 08:36 UTC, clementvtrd commented on App/src/Form/ExpenseType.php
> +        private Security $security
```suggestion
        private readonly Security $security
```

2024-09-11 08:58 UTC, LeoGrouet commented on App/src/DTO/ExpenseDTO.php
i know, but the PHPUnit PR isn't merge so i can't for now. But i will add them when the PHPunit PR will be ok

2024-09-11 09:01 UTC, LeoGrouet commented on App/src/Form/ExpenseType.php
> +        private Security $security
Fock. Done

2024-09-30 08:39 UTC, clementvtrd requested changes

2024-09-30 08:39 UTC, clementvtrd commented on App/.env.prod
![nope](https://i.giphy.com/ui4VjMUBGXhwgdwUnK.webp)

2024-09-30 08:39 UTC, clementvtrd commented on App/src/Entity/User.php
> +    }
Je ne pense pas que ça soit nécessaire :D

2024-10-01 08:46 UTC, clementvtrd approved these changes

2024-10-01 14:14 UTC, merged