Update expense
LeoGrouet/Qui-Paie-Quoi pull request #21
Opened 2024-10-11 07:45 UTC by LeoGrouet

2024-10-11 08:26 UTC, clementvtrd approved these changes

2024-10-11 08:26 UTC, clementvtrd commented on App/src/Service/ExpenseBalancer.php
>      }
When all your attributes are readonly you can make the entire class readonly. 😉 Except those which extends a non-readonly class

2024-10-11 08:26 UTC, clementvtrd requested changes
Wrong button 😭

2024-10-11 18:09 UTC, clementvtrd approved these changes

2024-10-11 18:09 UTC, clementvtrd commented on App/src/Service/ExpenseBalancer.php
> +    ) {}
```suggestion
final readonly class ExpenseBalancer
{
    public function __construct(
        private EntityManagerInterface $entityManager,
        private UserBalanceRepository $userBalanceRepository
    ) {}
```

2024-10-11 18:09 UTC, clementvtrd commented on App/src/Service/ExpenseBalancer.php
> +    ) {}
Presque !

2024-10-14 08:06 UTC, LeoGrouet commented on App/src/Service/ExpenseBalancer.php
> +    ) {}
Final ? C'est juste une notation ou ça a un intérêt particulier le final

2024-10-14 08:18 UTC, merged