Feature/show group
LeoGrouet/Qui-Paie-Quoi pull request #5
Opened 2024-05-17 14:08 UTC by LeoGrouet

2024-06-03 14:31 UTC, clementvtrd requested changes

2024-06-03 14:31 UTC, clementvtrd commented on App/migrations/Version20240523124411.php
Tu peux merger tes migrations :)

2024-06-03 14:31 UTC, clementvtrd commented on App/public/css/reset.css
D'où provient se reset ? 🤔

2024-06-03 14:31 UTC, clementvtrd commented on App/public/css/style.css
J'ai peur qu'utilisé les `vh` / `vw` soient pas assez prédictif sur le rendu final. Il vaudrait mieux utiliser des `em` (qui seront fixé par l'utilisateur via la valeur par défaut de la taille de police d'écriture) voir des `px` si la taille doit être fixée.

De plus je pense que ça peut être une bonne idée de tout de suite mettre en place des variables que tu pourras réutilisées plus tard pour avoir une cohérence au travers de ton application.

Par exemple tu réutilise `2vh` à plusieurs endroit, tu pourrais avoir une variable `--space-s` qui stockerait la valeur, avec ses variantes xs / s / m / l / xl à définir quand tu en auras besoin.

À noter les variables `--space-{size}` pourrait être utilisé partout où tu as la notion d'espace (margin, padding, gap, border width, etc...) ou bien définir un jeu de variable dédiée (e.g `--padding-s`)

2024-06-03 14:31 UTC, clementvtrd commented on App/src/Command/DatabaseFlushTest.php
> +        private UserRepository $userRepository
Ces attributs étant des services et n'étant pas voués à être modifiés, tu peux ajouter le modificateur `readonly` devant chacun d'eux

2024-06-03 14:31 UTC, clementvtrd commented on App/src/Command/DatabaseFlushTest.php
Je vois pas mal de redondance de code dans la manière dont tu créais tes entités. Tu peux probablement créer des fonctions privées pour factoriser un peu ta création d'entités

2024-06-03 14:31 UTC, clementvtrd commented on App/src/Command/HandleBalanceCommand.php
> +        private GroupExpenseBalancer $groupExpenseBalancer
Même retour ici, tu peux ajouter le modificateur `readonly`

2024-06-03 14:31 UTC, clementvtrd commented on App/src/Command/HandleBalanceCommand.php
As-tu vu que tu peux également proposer à la fonction `choice` une liste d'objet qui implémente la fonction `__toString` ? Je pense que tu pourrais directement passer la liste de tous les groupes à ta question, et la sélection te retournerait l'entité lié au texte choisis.

Source: https://symfony.com/doc/current/components/console/helpers/questionhelper.html#let-the-user-choose-from-a-list-of-answers

Tips: [l'interface native de PHP Stringable](https://www.php.net/manual/fr/class.stringable.php) normalise cette implémentation

2024-06-03 14:31 UTC, clementvtrd commented on App/src/Controller/GroupController.php
Tu peux probablement simplifier ton code en utilisant l'[EntityValueResolver](https://symfony.com/doc/current/doctrine.html#automatically-fetching-objects-entityvalueresolver) qui a été ajouté récemment 👍 
Nota bene: cela génèrera une page 404 si le groupe n'est pas trouvé, son implémentation correspond à la carte que tu as rajouté récemment au Trello 😉

2024-06-03 14:31 UTC, clementvtrd commented on App/src/Entity/User.php
> +        private string $password,
Comment as-tu choisi la longueur maximum de chaque champ ?

2024-06-03 14:31 UTC, clementvtrd commented on App/src/Repository/ExpenseRepository.php
>  }
Pour respecter la nomenclature des autres repositories, je te suggère de garder les méthodes pour récupérer des entités dans le style `find...` pour une collection et `findOne...` pour une entité seule.

Note aussi que le nom de ton argument doit aider à comprendre rapidement ce que l'on attend. `int $id` nous indique que nous attendons un `$id` mais cela peu être un peu léger. Avec `$groupId` on comprend tout de suite que la fonction a besoin de l'ID d'un groupe et rien d'autre.

```suggestion
    public function findByGroupId(int $groupId): array
    {
        return $this->createQueryBuilder('expense')
            ->where('expense.group = :groupId')
            ->setParameter('groupId', $groupId)
            ->getQuery()
            ->getResult();
    }
}
```

2024-06-03 14:31 UTC, clementvtrd commented on App/src/Repository/UserRepository.php
> +    public function getUserByName(string $name): User
Suite à ma suggestion plus haut

```suggestion
    public function findOneByName(string $name): User
```

2024-06-03 14:31 UTC, clementvtrd commented on App/src/Repository/UserRepository.php
> +    }
Plus globalement sur ta fonction, tu es censé n'avoir qu'un seul utilisateur avec un `name` donné. Dans le cas peu probable où deux utilisateurs ont le même nom, tu auras donc `null` comme valeur de retour.

Ce que je te propose, c'est de récupérer tous les utilisateurs qui ont le champ `name` correspond et ajouter une validation du type : si j'ai plus que un utilisateur alors j'émets une exception car ce n'est pas censé être possible ; sinon je retourne le seul utilisateur que j'ai ou null si j'en ai aucun.

De cette manière si le cas improbable se produit en base de données (pour X raison), tu seras en capacité de détecté cette erreur et la résoudre plus rapidement.

2024-06-03 14:31 UTC, clementvtrd commented on App/src/Service/GroupExpenseBalancer.php
> +        private ExpenseRepository $expenseRepository
Même remarque au sujet du modificateur `readonly` 😇 Plus spécifiquement, ici tous les attributs de ta classe seront `readonly`, tu peux donc rentre ta classe `readonly` 👍

2024-06-03 14:45 UTC, clementvtrd requested changes

2024-06-03 14:45 UTC, clementvtrd commented on App/src/Service/GroupExpenseBalancer.php
> +            $countParticipants = $participants->count();
De ce que je vois tu n'utilise pas la variable `$participants` ailleurs, tu peux sûrement gagner une assignation de variable ici 😉

2024-06-03 14:45 UTC, clementvtrd commented on App/src/Service/GroupExpenseBalancer.php
> +    private function updateParticipantOwe(Collection $participants, string $name, string $payerName, array $owe, int $amountByParticipants, Bilan $bilan, int $cost, int $participation): void
Peut être ajouté des sauts de lignes pour gagner en lisibilité

2024-06-03 14:45 UTC, clementvtrd commented on App/src/Service/GroupExpenseBalancer.php
> +                array_push($balances, ["userOwe" => $key, "amount" => $formatedValue, "to" => $name]);
Pareil pour tes déclarations de tableau : n'hésite pas à sauter des lignes quand ils contiennent plusieurs éléments, surtout quand ils sont associatifs, pour gagner en lisibilité 👍 

```suggestion
                $balances[] = [
                    "userOwe" => $key,
                    "amount" => $formatedValue,
                    "to" => $name,
                ];
```

2024-06-03 14:45 UTC, clementvtrd commented on App/templates/base.html.twig
> +        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%
D'où vient cette icon ? 🤔

2024-06-03 14:45 UTC, clementvtrd commented on App/templates/base.html.twig
> +        <title>{% block title %}Welcome!{% endblock %}</title>
Tu peux d'ors et déjà mettre le nom de ton application, ça ne mange pas de pain 👍

2024-06-03 14:45 UTC, clementvtrd commented on App/templates/error.html.twig
Vis à vis de mes premiers commentaires, peux être que ce template twig serait en réalité celui de l'erreur 404 générique (texte à adapter donc... 😇 )

2024-06-03 14:45 UTC, clementvtrd commented on App/templates/group.html.twig
Les classes CSS utilisées ici ont l'air de n'être utilisable qu'ici, ce que tu peux faire c'est créer une feuille de style dédié à cette page et l'injecter via le block `stylesheet` défini dans ton `base.html.twig`

2024-06-03 14:45 UTC, clementvtrd commented on Makefile
Penses à mettre à jour la documentation quand tu ajoute ce genre de raccourci. Cela sera très utile si jamais un autre développeur cherche à tester localement ton application 👍

2024-06-05 12:49 UTC, LeoGrouet commented on App/public/css/reset.css
J'avais enlevé la provenance en effet. Je l'ai remise. J'ai pris le reset CSS qu'on nous avait préconisé en formation.

2024-06-05 13:37 UTC, LeoGrouet commented on App/public/css/style.css
Okay, j'ai essayé d'adapter à ce que tu indique.

2024-06-05 13:38 UTC, LeoGrouet commented on App/src/Command/DatabaseFlushTest.php
> +        private UserRepository $userRepository
Done

2024-06-06 09:43 UTC, LeoGrouet commented on App/src/Command/HandleBalanceCommand.php
> +        private GroupExpenseBalancer $groupExpenseBalancer
Done.

2024-06-06 10:15 UTC, LeoGrouet commented on App/src/Entity/User.php
> +        private string $password,
Arbitrairement pour l'instant. 255 pour un nom, mail ou password me parraissait grand.

2024-06-07 14:59 UTC, merged

2024-06-17 12:20 UTC, LeoGrouet commented on App/src/Repository/UserRepository.php
> +    }
Cette fonction n'est même pas utilisé

2024-06-17 12:22 UTC, LeoGrouet commented on App/src/Service/GroupExpenseBalancer.php
> +            $countParticipants = $participants->count();
Done

2024-06-17 12:24 UTC, LeoGrouet commented on App/src/Service/GroupExpenseBalancer.php
> +    private function updateParticipantOwe(Collection $participants, string $name, string $payerName, array $owe, int $amountByParticipants, Bilan $bilan, int $cost, int $participation): void
done

2024-06-17 12:27 UTC, LeoGrouet commented on App/src/Service/GroupExpenseBalancer.php
> +                array_push($balances, ["userOwe" => $key, "amount" => $formatedValue, "to" => $name]);
done

2024-06-18 11:17 UTC, LeoGrouet commented on App/src/Command/DatabaseFlushTest.php
Done

2024-06-18 11:21 UTC, LeoGrouet commented on App/src/Service/GroupExpenseBalancer.php
> +        private ExpenseRepository $expenseRepository
done

2024-06-18 11:23 UTC, LeoGrouet commented on App/templates/base.html.twig
> +        <title>{% block title %}Welcome!{% endblock %}</title>
done

2024-06-18 11:24 UTC, LeoGrouet commented on App/templates/base.html.twig
> +        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%
De symfony , je l'ai supprimé

2024-06-18 11:26 UTC, LeoGrouet commented on App/src/Repository/ExpenseRepository.php
>  }
done

2024-06-18 11:29 UTC, LeoGrouet commented on App/src/Repository/UserRepository.php
> +    public function getUserByName(string $name): User
done

2024-06-18 11:42 UTC, LeoGrouet commented on Makefile
done

2024-06-18 11:51 UTC, LeoGrouet commented on App/templates/group.html.twig
done

2024-06-18 13:29 UTC, LeoGrouet commented on App/src/Command/HandleBalanceCommand.php
On regardera ensemble